string:
  port: 1121

integer:
  port: 1551

user:
  dir: configtest
  monitor: config
  jsondir: Club&config/clubConfig.json,Club1000&config/clubConfig100.json

sample:
  samplePackage: org.gars.mars.configtest.xlsx.sample
  samplePath: resources

db:
  link:
    url: jdbc:mysql://localhost:3306/test
    driver: com.mysql.jdbc.Driver
    username: root
    password: root

spring:
  redis:
    host: 192.168.1.100
    port: 6379
    password: alan
    # Redis数据库索引（默认为0）
    database: 4
    # 连接超时时间（毫秒）
    #    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0

logging:
  config: config/logback.xml
  level.*: debug